# Generated by Django 3.2.8 on 2021-12-26 22:21

from django.db import migrations, models
import django.db.models.constraints


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_quiz_slug'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='quizquestion',
            name='quiz_questions_order_unique',
        ),
        migrations.AddConstraint(
            model_name='quizquestion',
            constraint=models.UniqueConstraint(deferrable=django.db.models.constraints.Deferrable['DEFERRED'], fields=('quiz', 'question', 'order'), name='quiz_questions_order_unique'),
        ),
    ]
