# Generated by Django 3.2.8 on 2021-12-26 22:23

from django.db import migrations, models
import django.db.models.constraints


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_auto_20211226_2321'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='quizquestion',
            constraint=models.UniqueConstraint(deferrable=django.db.models.constraints.Deferrable['DEFERRED'], fields=('quiz', 'question'), name='quiz_questions_unique'),
        ),
    ]
