# Generated by Django 3.2.8 on 2021-12-03 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_alter_question_last_use'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='edited',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
